use github-scripts
Signed-off-by: Sunny Yip <sunny@kusari.dev>

diff --git a/.github/workflows/nightly_build.yaml b/.github/workflows/nightly_build.yaml
--- a/.github/workflows/nightly_build.yaml
+++ b/.github/workflows/nightly_build.yaml
@@ -35,53 +35,57 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # tag=v3
 
-      - name: Create and publish compose tarball
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          NIGHTLY_RELEASE_TAG_REF: "refs/tags/${{ env.NIGHTLY_RELEASE_TAG }}"
-        run: |
-          #!/usr/bin/env bash
-          set -euo pipefail
+      # - name: Create and publish compose tarball
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #     NIGHTLY_RELEASE_TAG_REF: "refs/tags/${{ env.NIGHTLY_RELEASE_TAG }}"
+      #   run: |
+      #     #!/usr/bin/env bash
+      #     set -euo pipefail
  
-          gh release list
-          gh release delete ${{ env.NIGHTLY_RELEASE_TAG }} --yes || true
-          git push --delete origin ${{ env.NIGHTLY_RELEASE_TAG }} || true
+      #     gh release list
+      #     gh release delete ${{ env.NIGHTLY_RELEASE_TAG }} --yes || true
+      #     git push --delete origin ${{ env.NIGHTLY_RELEASE_TAG }} || true
 
-      #- name: Advance nightly tag
-      #  uses: actions/github-script@v3
-      #  with:
-      #    # github-token: ${{secrets.GITHUB_TOKEN}}          
-      #    github-token: ${{ secrets.PAT_TAG_PUSHER }}
-      #    script: |
+      - name: Advance nightly tag
+        uses: actions/github-script@v3
+        with:
+          # github-token: ${{secrets.GITHUB_TOKEN}}          
+          github-token: ${{ secrets.PAT_TAG_PUSHER }}
+          script: |
 
-      #      try { 
-      #        github.git.deleteRef({
-      #          owner: context.repo.owner,
-      #          repo: context.repo.repo,
-      #          ref: "tags/v0.0.0-nightly"
-      #        })
-      #      } catch (error) { }
+            try { 
+              github.git.deleteRef({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                ref: "tags/v0.0.0-nightly"
+              })
+            } catch (error) { }
+            
+            const { owner, repo } = context.repo
+            // const { data: { id } } = await github.repos.getLatestRelease({ owner, repo })
+            await github.repos.deleteRelease({ owner, repo, release_id: ${{ env.NIGHTLY_RELEASE_TAG }} })
 
-      #      github.git.createRef({
-      #        owner: context.repo.owner,
-      #        repo: context.repo.repo,
-      #        ref: "refs/tags/v0.0.0-nightly",
-      #        sha: context.sha
-      #      })
+            github.git.createRef({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              ref: "refs/tags/v0.0.0-nightly",
+              sha: context.sha
+            })
 
-      - name: Push nightly tag
-        if: success() || failure()
-        env:
-          GITHUB_TOKEN: ${{ secrets.PAT_TAG_PUSHER }}
-        run: |
-          #!/usr/bin/env bash
-          set -euo pipefail
+      # - name: Push nightly tag
+      #   if: success() || failure()
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.PAT_TAG_PUSHER }}
+      #   run: |
+      #     #!/usr/bin/env bash
+      #     set -euo pipefail
 
-          git config --global user.email "runner@github.com"
-          git config --global user.name "Nightly Build Workflow"
+      #     git config --global user.email "runner@github.com"
+      #     git config --global user.name "Nightly Build Workflow"
 
-          git tag -a v0.0.0-nightly -m "scheduled nightly build at $(date -Iseconds)"
-          git push --tags
+      #     git tag -a v0.0.0-nightly -m "scheduled nightly build at $(date -Iseconds)"
+      #     git push --tags
 
 #      - name: Create and publish compose tarball
 #        env:
